import manifest from './image-manifest.json';

/**
 * The image registry.
 *
 * `image-manifest.json` is generated by `npm run images` (scripts/build-images.mjs):
 * it reads whatever photography is actually in /public/images, measures it,
 * makes a blur placeholder, and attaches the credit line. Nothing here is
 * hand-maintained except the curation in that script.
 *
 * Apartment slots are declared even when the photograph has not arrived yet —
 * an empty slot renders as a designed placeholder rather than a broken layout,
 * so the site can go live section by section as photography comes in.
 */

export type ImageCategory = 'apartment' | 'lovere' | 'lake';

export type Credit = {
  author: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
};

export type SiteImage = {
  id: string;
  /** Absent when the photograph has not been supplied yet. */
  src: string | null;
  width: number;
  height: number;
  blurDataURL: string | null;
  category: ImageCategory;
  section: string;
  alt: { en: string; it: string };
  credit: Credit | null;
  /** Focal point for object-position, as percentages. */
  focus?: { x: number; y: number };
};

const images = manifest.images as SiteImage[];

export const allImages = images;

export function image(id: string): SiteImage {
  const found = images.find((i) => i.id === id);
  if (found) return found;
  // A missing id is a content bug, not a crash: render a placeholder slot.
  return {
    id,
    src: null,
    width: 1600,
    height: 1067,
    blurDataURL: null,
    category: 'apartment',
    section: 'unknown',
    alt: { en: '', it: '' },
    credit: null,
  };
}

export function bySection(section: string): SiteImage[] {
  return images.filter((i) => i.section === section);
}

export function byCategory(category: ImageCategory): SiteImage[] {
  return images.filter((i) => i.category === category);
}

/** Present photographs only — used wherever an empty slot would look broken. */
export function present(list: SiteImage[]): SiteImage[] {
  return list.filter((i) => i.src);
}

export function altFor(img: SiteImage, locale: string): string {
  return (img.alt as Record<string, string>)[locale] ?? img.alt.en;
}

/** Everything with a licence attribution, for the credits page. */
export function creditedImages(): SiteImage[] {
  return images.filter((i) => i.credit && i.src);
}

export const heroImageId = manifest.heroImageId as string;
export const ogImageId = manifest.ogImageId as string;
